version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    depends_on:
      - db    

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: devpass123
      MYSQL_DATABASE: lab_py_web
      MYSQL_USER: lab_user
      MYSQL_PASSWORD: lab_pass123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
 mysql_data:  